web_team3_assignment/Models/StudentSuggestionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace web_team3_assignment.Models
{
    public class StudentSuggestionViewModel
    {
        [Display(Name = "Suggestion ID")]
        public int SuggestionId { get; set; }

        [Display(Name = "Lecturer ID")]
        public int LecturerId { get; set; }

        [Display(Name = "Student ID")]
        public int StudentId { get; set; }

        [Required(ErrorMessage = "Fill in the Description!")]
        [StringLength(3000, ErrorMessage = "Description Cannot Exceed 3000 Characters!")]
        public string Description { get; set; }

        public string Status { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime DateCreated { get; set; }

        [Display(Name = "Lecturer Name")]
        [StringLength(50, ErrorMessage = "Password Length Cannot Exceed 50 Characters!")]
        public string LecturerName { get; set; }
    }
}

web_team3_assignment/Models/Suggestion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace web_team3_assignment.Models
{
    public class Acknowledge
    {
        //public char Status { get; set; }
        //public IEnumerable<SelectListItem> StatusList
        //{
        //    get
        //    {
        //        List<SelectListItem> list = new List<SelectListItem>
        //        {
        //            new SelectListItem() { Text = "Acknowledge", Value = "Y"},
        //            new SelectListItem() { Text = "Not Acknowledged", Value = "N" }
        //        };
        //        return list.Select(l => new SelectListItem { Selected = (l.Value == Status.ToString()), Text = l.Text, Value = l.Value });
        //    }
        //}
    }

    public class Suggestion
    {
        [Display(Name = "Suggestion ID:")]
        public int SuggestionId { get; set; }

        [Display(Name = "Lecturer ID:")]
        public int LecturerId { get; set; }

        [Display(Name = "Choose Your Mentee:")]
        public int StudentId { get; set; }

        [Required(ErrorMessage = "Fill in the Description!")]
        [StringLength(3000, ErrorMessage = "Description Cannot Exceed 3000 Characters!")]
        public string Description { get; set; }

        public char Status { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime DateCreated { get; set; }

    }
}

web_team3_assignment/Models/SuggestionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace web_team3_assignment.Models
{
    public class SuggestionViewModel
    {
        [Display(Name = "Suggestion ID")]
        public int SuggestionId { get; set; }

        [Display(Name = "Lecturer ID")]
        public int LecturerId { get; set; }

        [Display(Name = "Student ID")]
        public int StudentId { get; set; }

        [Required(ErrorMessage = "Fill in the Description!")]
        [StringLength(3000, ErrorMessage = "Description Cannot Exceed 3000 Characters!")]
        public string Description { get; set; }

        public string Status { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime DateCreated { get; set; }

        [Display(Name = "Student Name")]
        public string StudentName { get; set; }
    }
}

web_team3_assignment/Controllers/SuggestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web_team3_assignment.DAL;
using web_team3_assignment.Models;
using System.Diagnostics;

namespace web_team3_assignment.Controllers
{
    public class SuggestionController : Controller
    {
        private LecturerDAL lecturerContext = new LecturerDAL();
        private SuggestionDAL suggestionContext = new SuggestionDAL();
        private StudentDAL studentContext = new StudentDAL();
        // View All Suggestion Posted by the Currently Logged In Lecturer
        // GET: Suggestion
        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<SuggestionViewModel> suggestionVMList = new List<SuggestionViewModel>();
            List<Suggestion> suggestionList = suggestionContext.GetSuggestionPostedByMentor(Convert.ToInt32(HttpContext.Session.GetString("ID")));
            foreach(Suggestion suggestion in suggestionList)
            {
                SuggestionViewModel suggestionVM = MapToStudentVM(suggestion);
                suggestionVMList.Add(suggestionVM);
            }
            return View(suggestionVMList);
        }
   
        public SuggestionViewModel MapToStudentVM(Suggestion suggestion)
        {
            if (suggestion != null)
            {
                string studentName = "";
                List<Student> studentList = studentContext.GetAllStudent();
                foreach (Student student in studentList)
                {
                    if (student.StudentID == suggestion.StudentId)
                    {
                        studentName = student.Name;
                        break;
                    }
                }
                string suggestionStatus;
                if (suggestion.Status == 'N')
                {
                    suggestionStatus = "Not Acknowledged";
                }
                else
                {
                    suggestionStatus = "Acknowledged";
                }
                SuggestionViewModel suggestionVM = new SuggestionViewModel
                {
                    SuggestionId = suggestion.SuggestionId,
                    LecturerId = suggestion.LecturerId,
                    Description = suggestion.Description,
                    Status = suggestionStatus,
                    DateCreated = suggestion.DateCreated,
                    StudentName = studentName
                };
                return suggestionVM;
            }
            else
                return null;
        }

        public StudentSuggestionViewModel MapToLecturerVM(Suggestion suggestion)
        {
            if (suggestion != null)
            {
                string lecturerName = "";
                List<Lecturer> lecturerList = lecturerContext.GetAllLecturer();
                Student student = studentContext.GetStudentDetails(Convert.ToInt32(HttpContext.Session.GetInt32("StudentID")));
                foreach (Lecturer lecturer in lecturerList)
                {
                    if (lecturer.LecturerId == suggestion.LecturerId && lecturer.LecturerId == student.MentorID && student.StudentID == suggestion.StudentId)
                    {
                        lecturerName = lecturer.Name;
                        break;
                    }
                }
                string suggestionStatus;
                if (suggestion.Status == 'N')
                {
                    suggestionStatus = "Not Acknowledged";
                }
                else
                {
                    suggestionStatus = "Acknowledged";
                }
                StudentSuggestionViewModel studentVM = new StudentSuggestionViewModel
                {
                    SuggestionId = suggestion.SuggestionId,
                    LecturerId = suggestion.LecturerId,
                    StudentId = suggestion.StudentId,
                    Description = suggestion.Description,
                    Status = suggestionStatus,
                    DateCreated = suggestion.DateCreated,
                    LecturerName = lecturerName
                };
                return studentVM;
            }
            else
                return null;
        }

        // GET: Suggestion
        public ActionResult StudentSuggestion()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Student"))
            {
                return RedirectToAction("Index", "Home");
            }
            int studentid = Convert.ToInt32(HttpContext.Session.GetInt32("StudentID"));
            List<StudentSuggestionViewModel> studentsuggestionVMList = new List<StudentSuggestionViewModel>();
            List<Suggestion> suggestionList = suggestionContext.GetSuggestionPostedByStudentsMentor(Convert.ToInt32(HttpContext.Session.GetInt32("StudentID")));
            foreach (Suggestion suggestion in suggestionList)
            {
                StudentSuggestionViewModel suggestionVM = MapToLecturerVM(suggestion);
                studentsuggestionVMList.Add(suggestionVM);
            }
            return View(studentsuggestionVMList);
        }

        // GET: Suggestion/Acknowledge/5
        public ActionResult Acknowledge(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Student"))
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                TempData["ErrorMessage"] = "You are not allowed to acknowledge other student's suggestions!";
                return RedirectToAction("Index");
            }
            int studentid = Convert.ToInt32(HttpContext.Session.GetInt32("StudentID"));
            Suggestion suggestion = suggestionContext.GetSuggestionDetails(id.Value);
            StudentSuggestionViewModel suggestionVM = MapToLecturerVM(suggestion);
            if (suggestion == null || suggestion.StudentId != studentid)
            {
                TempData["ErrorMessage"] = "You are not allowed to acknowledge other student's suggestions!";
                return RedirectToAction("StudentSuggestion");
            }
            return View(suggestionVM);
        }

        // POST: Suggestion/Acknowledge/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Acknowledge(Suggestion suggestion)
        {
            // Acknowledge the Suggestion using a method called Acknowledge
            suggestionContext.Acknowledge(suggestion.SuggestionId);
            return RedirectToAction("StudentSuggestion");
        }
        
        // Post Suggestion Page
        // GET: Suggestion/PostSuggestion
        public ActionResult PostSuggestion()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["MenteeList"] = lecturerContext.GetMentees(Convert.ToInt32(HttpContext.Session.GetString("ID")));
            return View();
        }

        // POST: Suggestion/PostSuggestion
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostSuggestion(Suggestion suggest)
        {
            int lecturerid = Convert.ToInt32(HttpContext.Session.GetString("ID"));
            List<SelectListItem> menteeList = new List<SelectListItem>(lecturerContext.GetMentees(lecturerid));
            if (menteeList.Count() == 0)
            {
                ViewData["Message"] = "You Must Have A Mentee To Post!";
                return View();
            }
            ViewData["MenteeList"] = menteeList;
            suggest.LecturerId = lecturerid;
            suggest.Status = 'N';
            if (ModelState.IsValid)
            {
                suggest.SuggestionId = suggestionContext.PostSuggestion(suggest);
                ViewData["Message"] = "Suggestion Posted Successfully";
                return View();
            }
            else
            {
                return View(suggest);
            }
        }
        // Edit Suggestion Page
        // GET: Suggestion/Edit/5
        public ActionResult Edit(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return RedirectToAction("Index");
            }

            //gets the suggestion information based on the URL ID
            Suggestion suggestion = suggestionContext.GetSuggestionDetails(id.Value);
            //if the suggestion cannot be found, return null and return a message to the index action
            if (suggestion == null)
            {
                TempData["Message"] = "The Suggestion does not exist!";
                return RedirectToAction("Index");
            }
            //if the suggestion's lecturer id does not match with the logged in lecturer's ID
            if (suggestion.LecturerId != Convert.ToInt32(HttpContext.Session.GetString("ID")))
            {
                TempData["Message"] = "You are not allowed to edit other lecturer's suggestion!";
                return RedirectToAction("Index");
            }
            //if all validations are ok, return the page with the suggestion mapped properly with proper fields
            SuggestionViewModel suggestionVM = MapToStudentVM(suggestion);

web_team3_assignment/Views/Suggestion/Acknowledge.cshtml
@model web_team3_assignment.Models.StudentSuggestionViewModel

@{
    ViewData["Title"] = "Acknowledge";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form asp-action="Acknowledge">
    <fieldset class="FormContent">
        <legend>Are you sure you want to acknowledge this suggestion??</legend>
        <div class="form-group row">
            <label asp-for="SuggestionId" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SuggestionId" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="LecturerName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="LecturerName" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Description" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Description" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Status" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Status" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DateCreated" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="DateCreated" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Acknowledge" class="btn btn-primary mb1 bg-teal" />
            </div>
        </div>
        <div>
            <a asp-action="StudentSuggestion" class="btn btn-primary mb1 black bg-gray">Back to List</a>
        </div>
    </fieldset>
</form>

web_team3_assignment/Views/Suggestion/Delete.cshtml
@model web_team3_assignment.Models.SuggestionViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="img-fluid" src="~/images/deletesuggestion.png" style="display:block; margin:auto;" />
<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="SuggestionId" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SuggestionId" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StudentName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="StudentName" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Description" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Description" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Status" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-6">
                <input asp-for="Status" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DateCreated" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="DateCreated" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete" class="btn btn-primary mb1 bg-teal" />
                <br />
                @if (Model.Status == "Not Acknowledged")
                {
                    <span style="font-weight:bold; color: brown; padding-left:5px;">WARNING: This Suggestion Has Not Been Acknowledged Yet!</span>
                }
            </div>
        </div>
    <div>
            <a asp-action="Index" class="btn btn-primary mb1 black bg-gray">Back to List</a>
    </div>
</fieldset>
</form>

web_team3_assignment/Views/Suggestion/Edit.cshtml
@model web_team3_assignment.Models.SuggestionViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="img-fluid" src="~/images/editsuggestion.png" style="display:block; margin:auto;" />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="SuggestionId" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                <input asp-for="SuggestionId" readonly class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="StudentName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                <input asp-for="StudentName" readonly class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Description" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                <textarea rows="4" cols="40" asp-for="Description" class="form-control"></textarea>
                @if (ViewData["Message"] != null)
                {
                    <span class="text-danger">@ViewData["Message"]</span>
                }
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Status" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                <select asp-for="Status" id="status" class="col-sm-9 form-control">
                    <option value='Y' id="acknowledged">Acknowledged</option>
                    <option value='N' id="nacknowledged">Not Acknowledged</option>
                </select>                
                @if (Model.Status == "Acknowledged")
                {
                    <script>
                        document.getElementById("acknowledged").selected = "true";
                    </script>
                }
                else
                {
                    <script>
                        document.getElementById("nacknowledged").selected = "false";
                    </script>
                }
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DateCreated" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                <input asp-for="DateCreated" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save" class="btn btn-primary mb1 bg-teal" />
            </div>
        </div>
        <div>
            <a asp-action="Index" class="btn btn-primary mb1 black bg-gray">Back to List</a>
        </div>
    </fieldset>
</form>

web_team3_assignment/Views/Suggestion/Index.cshtml
@model IEnumerable<web_team3_assignment.Models.SuggestionViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="img-fluid" src="~/images/viewsuggestion.png" style="display:block; margin:auto;" />
<a asp-action="PostSuggestion"><img class="img-fluid" src="~/images/postsuggestion.gif" style="display:block; margin:auto;" /></a>
@if (TempData["Message"] != null)
{
    <h3 class="text-danger" style="text-align:center;">@TempData["Message"]</h3>
}
@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Student Name</th>
                    <th>Description</th>
                    <th>Date Created</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    string selectedRow = "";
                    if (item.Status == "Acknowledged")
                    {
                        selectedRow = "class='table-success'";
                    }
                    else if (item.Status == "Not Acknowledged")
                    {
                        selectedRow = "class='table-danger'";
                    }
                    <tr @Html.Raw(selectedRow)>
                        <td>@item.SuggestionId.ToString()</td>
                        <td>@item.StudentName</td>
                        <td>@item.Description</td>
                        <td>@item.DateCreated.ToString()</td>
                        <td>@item.Status</td>
                        <td>
                            <a asp-action="Edit" asp-controller="Suggestion"
                               asp-route-id="@item.SuggestionId">Edit</a> |
                            <a asp-action="Delete" asp-controller="Suggestion"
                               asp-route-id="@item.SuggestionId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

web_team3_assignment/Views/Suggestion/PostSuggestion.cshtml
@model web_team3_assignment.Models.Suggestion

@{
    ViewData["Title"] = "PostSuggestion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="~/images/postsuggestionstatic.png" style="display:block; margin:auto;" class="img-fluid" />
<form asp-action="PostSuggestion">
    <fieldset class="FormContent">
        <legend>Key in a Suggestion to a Mentee Below</legend>
        <div class="form-group row">
            <label asp-for="StudentId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-4">
                <select asp-for="StudentId"
                        asp-items="@ViewData["MenteeList"] as List<SelectListItem>"
                        class="form-control"></select>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Description"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-4">
                <textarea asp-for="Description" class="form-control" rows="4" cols="40"></textarea>
                <span asp-validation-for="Description"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Post Suggestion"
                       class="btn btn-primary" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">

                @if (ViewData["Message"] != null)
                {
                    <span class="text-danger">@ViewData["Message"]</span>
                }
            </div>
        </div>
        <div>
            <a asp-action="Index" class="btn btn-primary mb1 black bg-gray">Back</a>
        </div>

    </fieldset>
    </form>

web_team3_assignment/Views/Suggestion/StudentSuggestion.cshtml
@model IEnumerable<web_team3_assignment.Models.StudentSuggestionViewModel>

@{
    ViewData["Title"] = "StudentSuggestion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<img class="img-fluid" src="~/images/viewsuggestion.png" style="display:block; margin:auto;" />
@if (TempData["ErrorMessage"] != null)
{
    <h3 style="font-weight:bold; color:red; text-align:center;">@TempData["ErrorMessage"]</h3>
}

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Lecturer Name</th>
                    <th>Description</th>
                    <th>Date Created</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.SuggestionId.ToString()</td>
                        <td>@item.LecturerName</td>
                        <td>@item.Description</td>
                        <td>@item.DateCreated.ToString()</td>
                        <td>@item.Status</td>
                        <td>
                            <a asp-action="Acknowledge" asp-controller="Suggestion"
                               asp-route-id="@item.SuggestionId">Acknowledge</a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a class="btn btn-primary mb1 black bg-gray" href="~/Home/StudentMain">Back</a>
    </div>
}