web_team3_assignment/Models/ProjectMember.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace web_team3_assignment.Models
{
    public class ProjectMember
    {
        [Required]
        [Display(Name = "Project ID")]
        public int ProjectId { get; set; }

        [Required]
        [Display(Name = "Student ID")]
        public int StudentId { get; set; }

        [Required]
        [Display(Name = "Role")]
        [StringLength(50, ErrorMessage = "Cannot Exceed 50 Characters")]
        public string Role { get; set; }
    }
}

web_team3_assignment/Models/ProjectMemberViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace web_team3_assignment.Models
{
    public class ProjectMemberViewModel
    {
        public List<ProjectMember> projectMemberList { get; set; }
        public List<Project> projectList { get; set; }
    }
}

web_team3_assignment/Controllers/ProjectMemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web_team3_assignment.DAL;
using web_team3_assignment.Models;

namespace web_team3_assignment.Controllers
{
    public class ProjectMemberController : Controller
    {
        private ProjectDAL projectContext = new ProjectDAL();
        private ProjectMemberDAL projectMemberContext = new ProjectMemberDAL();


        public ActionResult Index(int? id)
        {
            // Stop accessing the action if not logged in 
            // or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Student"))
            {
                return RedirectToAction("Index", "Home");
            }

            ProjectMemberViewModel projectMemberVM = new ProjectMemberViewModel();
            projectMemberVM.projectMemberList = projectMemberContext.GetAllProjectMembers();

            // BranchNo (id) present in the query string
            if (id != null)
            {
                ViewData["selectedProjectId"] = id.Value;
                projectMemberVM.projectList = projectMemberContext.GetProjectPM(id.Value);
            }
            else
            {
                ViewData["selectedProjectId"] = "";
            }
            return View(projectMemberVM);

            //return View();
        }
    }
}

web_team3_assignment/Views/ProjectMember/Index.cshtml
@model web_team3_assignment.Models.ProjectMemberViewModel

@{
    ViewData["Title"] = "View ProjectMembers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="PageTitle">View ProjectMember</h4>
<!-- Display a list of projectmembers -->
<div class="table-responsive">
    <table id="viewProjectMember" class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ProjectID</th>
                <th>StudentID</th>
                <th>Role</th>
                @*<th></th>*@
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.projectMemberList)
            {
                string selectedRow = "";
                if (ViewData["selectedProjectID"].ToString()
                 == item.ProjectId.ToString())
                {
                    // Highlight the selected row
                    selectedRow = "class='table-primary'";
                }
            <tr @Html.Raw(selectedRow)>
                <td>@item.ProjectId.ToString()</td>
                <td>@item.StudentId.ToString()</td>
                <td>@item.Role</td>
                @*<td>
                    <a asp-action="Index" asp-controller="ProjectMember"
                       asp-route-id="@item.ProjectId">View Project</a>
                </td>*@
            </tr>
            }
        </tbody>
    </table>
</div>
 @*Display a list of project for each projectmembers 
@if (ViewData["selectedProjectID"].ToString() != "")
{
    if (Model.projectList.Count != 0)
    {
        <h5>
            ProjectMembers working under the Project
            @ViewData["selectedProjectID"].ToString() :
        </h5>
        <partial name="~/Views/Project/_ViewProject.cshtml"
                 model="@Model.projectList" />
    }
    else
    {
        <h5>No project for selected projectmembers!</h5>
    }
}*@